install.packages("arules")
library(arules)
data("Groceries")
class(Groceries)
summary(Groceries)
inspect(Groceries[1:5])
itemFrequency(Groceries[,1:3])
itemFrequencyPlot(Groceries,support=0.1)
itemFrequencyPlot(Groceries,topN=20)
groceryrules <- apriori(Groceries,parameter = list(support=0.01,confidence=0.2, 
                                                   minlen=2))
summary(groceryrules)
inspect(groceryrules[1:5])
inspect(sort(groceryrules,by = "lift")[1:5])
berryrules <- subset(groceryrules, items %in% "berries")
inspect(berryrules)
write(groceryrules,file = "groceryrules.csv",
      sep=",", quote= TRUE, row.names=FALSE)
groceryrules_df <- as(groceryrules, "data.frame")
str(groceryrules_df)
